const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { Store } = require('../src/main/store');
const { generateFingerprint } = require('../src/main/fingerprints');
const { settingsFor, validateSettings } = require('../src/main/fingerprint-settings');
const { alignStoredProfile } = require('../src/main/profile-compatibility');
const { buildLaunchConfig } = require('../src/main/launch-config');
const { applyProfileSettings } = require('../src/main/chrome-profile');

const hardware = { os: 'windows', platform: 'Win32', hints: { platform: 'Windows', platformVersion: '19.0.0', architecture: 'x86', bitness: '64' }, webgl: { vendor: 'Google Inc. (Intel)', renderer: 'Measured Intel GPU' }, hardwareConcurrency: 12, deviceMemory: 16, devicePixelRatio: 1.5, screen: { width: 1280, height: 720, availWidth: 1280, availHeight: 672, colorDepth: 24, pixelDepth: 24 } };
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bm-editor-test-'));
try {
  const store = new Store(root);
  let profile = store.createProfile({ name: 'Manual identity', os: 'windows', locale: 'auto', color: '#1a73e8', noiseSeed: '0123456789abcdef', fingerprint: generateFingerprint({ hardware, engineVersion: '154.0.8037.98' }) });
  const originalId = profile.id;
  const marker = path.join(store.userDataDir(profile.id), 'session-marker');
  fs.writeFileSync(marker, 'keep this session');
  const s = settingsFor(profile);
  s.webgl = { mode: 'custom', vendor: 'Google Inc. (NVIDIA)', renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002484) Direct3D11 vs_5_0 ps_5_0, D3D11)' };
  s.webgpu.mode = 'webgl'; s.cpu = { mode: 'custom', value: 8 }; s.memory = { mode: 'custom', value: 8 };
  s.screen = { mode: 'custom', width: 1920, height: 1080, availWidth: 1920, availHeight: 1040 };
  s.timezone = { mode: 'custom', value: 'Asia/Tokyo' };
  s.location = { mode: 'custom', lat: 35, lon: 139, accuracy: 50, permission: 'allow' };
  s.noise = { canvas: false, webgl: true, audio: false, clientRects: true, speechVoices: false };
  s.fonts = { mode: 'custom', allowed: ['Garamond', 'GARAMOND', 'Rockwell'] };
  s.webrtc = 'disabled'; s.doNotTrack = 'on'; s.acceleration = 'off';
  profile = store.updateProfile(profile.id, { fingerprintSettings: validateSettings(s, profile) });
  profile = alignStoredProfile(store, profile, hardware, '154.0.8037.98');
  assert.equal(profile.id, originalId); assert.equal(profile.noiseSeed, '0123456789abcdef');
  assert.equal(fs.readFileSync(marker, 'utf8'), 'keep this session');
  assert.equal(profile.fingerprint.fingerprint.videoCard.renderer, s.webgl.renderer);
  assert.equal(profile.fingerprint.fingerprint.navigator.hardwareConcurrency, 8);
  assert.equal(profile.fingerprint.fingerprint.screen.width, 1920);
  // Relaunch alignment must retain custom settings, with no new backup or seed.
  assert.strictEqual(alignStoredProfile(store, profile, hardware, '154.0.8037.98'), profile);
  const config = buildLaunchConfig(profile, { systemLocale: 'en-US' });
  assert.equal(config.nativeConfig.webgl.vendor, s.webgl.vendor);
  assert.deepEqual(config.nativeConfig.webgpu, { custom: true, vendor: 'nvidia', architecture: '', device: '00002484', description: '' });
  assert.deepEqual(config.nativeConfig.noise, { ...s.noise, fonts: false });
  assert.deepEqual(config.nativeConfig.fontAllowlist, ['garamond', 'rockwell']);
  assert.equal(config.nativeConfig.timezone, 'Asia/Tokyo');
  assert.deepEqual(config.nativeConfig.geo, { lat: 35, lon: 139, accuracy: 50 });
  assert.equal(config.nativeConfig.webrtcDisabled, true);
  applyProfileSettings(store.userDataDir(profile.id), { name: profile.name, color: profile.color, languages: config.languages, ...config });
  const prefs = JSON.parse(fs.readFileSync(path.join(store.userDataDir(profile.id), 'Default/Preferences')));
  assert.equal(prefs.profile.default_content_setting_values.geolocation, 1);
  assert.equal(prefs.enable_do_not_track, true);
  const local = JSON.parse(fs.readFileSync(path.join(store.userDataDir(profile.id), 'Local State')));
  assert.equal(local.hardware_acceleration_mode.enabled, false);
  const invalid = structuredClone(s); invalid.screen.availWidth = 2000;
  assert.throws(() => validateSettings(invalid, profile), /cannot exceed/);
  invalid.screen.availWidth = 1920; invalid.timezone.value = 'Imaginary/Timezone';
  assert.throws(() => validateSettings(invalid, profile), /valid timezone/);
  const real = settingsFor(profile); real.webgl.mode = 'real'; real.webgpu.mode = 'disabled'; real.cpu.mode = real.memory.mode = real.screen.mode = 'real';
  real.location.mode = 'block'; real.timezone.mode = 'real'; real.fonts.mode = 'real'; real.doNotTrack = 'default'; real.acceleration = 'default';
  for (const key of Object.keys(real.noise)) real.noise[key] = false;
  profile = store.updateProfile(profile.id, { fingerprintSettings: validateSettings(real, profile), locale: 'real' });
  profile = alignStoredProfile(store, profile, hardware, '154.0.8037.98');
  const realConfig = buildLaunchConfig(profile, { systemLocale: 'ar-SA' });
  assert.equal(realConfig.nativeConfig.webgl, undefined);
  assert.deepEqual(realConfig.nativeConfig.webgpu, { disabled: true });
  assert.equal(realConfig.nativeConfig.noiseSeed, undefined);
  assert.equal(realConfig.nativeConfig.timezone, undefined); assert.equal(realConfig.nativeConfig.geo, undefined);
  assert.equal(realConfig.locationPermission, 2); assert.equal(realConfig.language, 'ar-SA');
  assert.equal(profile.noiseSeed, '0123456789abcdef');
  assert.equal(profile.fingerprint.fingerprint.navigator.hardwareConcurrency, 12);
  assert.equal(profile.fingerprint.fingerprint.screen.width, 1280);
  applyProfileSettings(store.userDataDir(profile.id), { name: profile.name, color: profile.color, ...realConfig });
  const reset = JSON.parse(fs.readFileSync(path.join(store.userDataDir(profile.id), 'Default/Preferences')));
  assert.equal(reset.enable_do_not_track, undefined); assert.equal(reset.profile.default_content_setting_values.geolocation, 2);
  console.log('PASS: manual GPU/CPU/RAM/screen choices persist across alignment; native WebGPU/noise/location/WebRTC configuration, browser preferences, validation and Real-mode resets are correct; session and seed preserved.');
} finally { fs.rmSync(root, { recursive: true, force: true }); }
